[package]
name = "news_boy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lapin = "*"
tokio = "*"
tracing = "*"
tracing-subscriber = "*"
futures = "*"
async-global-executor = "*"
getopts = "0.2"